name: CI/CD workflow

on: workflow_dispatch

jobs:
  integration:
    name: continuous-integration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code repo
      uses: actions/checkout@v4

    - name: Setup uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Install dependencies
      run: uv sync --group integration

    - name: Run ruff check
      run: uv run ruff check

    - name: Run pip-audit
      run: uv run pip-audit --vulnerability-service pypi

    - name: Run PyTest
      run: uv run pytest tests
